-- Generated by OntologyMirror
-- Standard: Schema.org

-- Source: auth_user
-- Rationale: Detected user-related fields.
CREATE TABLE Person (
    alternateName        TEXT, -- from username,
    email                TEXT, -- from email
);

-- Source: blog_post
-- Rationale: Detected blog-related keywords.
CREATE TABLE BlogPosting (
    headline             TEXT, -- from title,
    articleBody          TEXT, -- from content
);
