-- Generated by OntologyMirror
-- Standard: Schema.org

-- Source: users
-- Rationale: Detected user-related fields.
CREATE TABLE Person (
    alternateName        TEXT, -- from username,
    email                TEXT, -- from email
);

-- Source: orders
-- Rationale: Detected order-related keywords.
CREATE TABLE Order (
    orderNumber          TEXT, -- from order_id,
    totalPaymentDue      TEXT, -- from amount
);

-- Source: auth_user
-- Rationale: Detected user-related fields.
CREATE TABLE Person (
    alternateName        TEXT, -- from username,
    email                TEXT, -- from email
);

-- Source: blog_post
-- Rationale: Detected blog-related keywords.
CREATE TABLE BlogPosting (
    headline             TEXT, -- from title,
    articleBody          TEXT, -- from content
);
